import "./globals.css";
import { ThemeProvider } from "./components/darkMode/ThemeProvider";
import { Geist, Geist_Mono } from "next/font/google";
import ReduxProvider from "./store/Provider";
import ToastProvider from "./components/toast/ToastProvider";
import CartPersistence from "./components/shoppingCart/Persistence";
import AuthProvider from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider>
            <ReduxProvider>
              <ToastProvider>
                <CartPersistence />
                {children}
              </ToastProvider>
            </ReduxProvider>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
