import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import ReduxProvider from "./store/Provider";
import DarkModeProvider from "./components/darkMode/DarkModeProvider";
import ToastProvider from "./components/toast/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black dark:bg-zinc-900 dark:text-white`}
      >
        <DarkModeProvider>
          <ReduxProvider>
            <ToastProvider>
              {children}
            </ToastProvider>
          </ReduxProvider>
        </DarkModeProvider>
      </body>
    </html>
  );
}
