import type { Metadata } from "next";
import type { ReactNode } from "react";

import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { ThemeProvider } from "./components/darkMode/ThemeProvider";
import ToastProvider from "./components/toast/ToastProvider";
import CartPersistence from "./components/shoppingCart/Persistence";
import AuthProvider from "./context/AuthContext";
import ReduxProvider from "./store/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({
  children,
}: RootLayoutProps) {
  return (
    <html
      lang="fa"
      dir="rtl"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider>
            <ReduxProvider>
              <ToastProvider>
                <CartPersistence />
                {children}
              </ToastProvider>
            </ReduxProvider>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}